[Interface]
PrivateKey = sEGNZ5iWcxevqwdITi8hU9tc7e2uBAWq3lSx8DZX3UQ=
Address = 10.8.0.2/24
DNS = 1.1.1.1, 1.0.0.1
Jc = 4
Jmin = 40
Jmax = 70
S1 = 40
S2 = 70
H1 = 1
H2 = 2
H3 = 3
H4 = 4

[Peer]
PublicKey = o+4gSRR9IWt2f5BGXeI3rTTC+19pljk909N02ESD10M=
PresharedKey = sdC0qygWIWQbjvIgxf88Be6mivfdtekSUHjio4MXZoO=
Endpoint = 199.119.137.193:4500
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 15
